/***********************************I-DEP-RAC-SEGDOC-0-01/02/2017*****************************************/
select pxp.f_insert_testructura_gui ('SEGDOC', 'SISTEMA');
select pxp.f_insert_testructura_gui ('TDO', 'SEGDOC');
select pxp.f_insert_testructura_gui ('RDOC', 'SEGDOC');
select pxp.f_insert_testructura_gui ('VBDOC', 'SEGDOC');
select pxp.f_insert_testructura_gui ('RDOC.1', 'RDOC');
select pxp.f_insert_testructura_gui ('RDOC.2', 'RDOC');
select pxp.f_insert_testructura_gui ('RDOC.3', 'RDOC');
select pxp.f_insert_testructura_gui ('RDOC.4', 'RDOC');
select pxp.f_insert_testructura_gui ('RDOC.5', 'RDOC');
select pxp.f_insert_testructura_gui ('RDOC.1.1', 'RDOC.1');
select pxp.f_insert_testructura_gui ('RDOC.1.1.1', 'RDOC.1.1');
select pxp.f_insert_testructura_gui ('RDOC.1.1.2', 'RDOC.1.1');
select pxp.f_insert_testructura_gui ('RDOC.1.1.3', 'RDOC.1.1');
select pxp.f_insert_testructura_gui ('RDOC.1.1.4', 'RDOC.1.1');
select pxp.f_insert_testructura_gui ('RDOC.1.1.5', 'RDOC.1.1');
select pxp.f_insert_testructura_gui ('RDOC.4.1', 'RDOC.4');
select pxp.f_insert_testructura_gui ('RDOC.4.1.1', 'RDOC.4.1');
select pxp.f_insert_testructura_gui ('RDOC.4.1.2', 'RDOC.4.1');
select pxp.f_insert_testructura_gui ('RDOC.4.1.3', 'RDOC.4.1');
select pxp.f_insert_testructura_gui ('RDOC.4.1.1.1', 'RDOC.4.1.1');
select pxp.f_insert_testructura_gui ('RDOC.4.1.1.1.1', 'RDOC.4.1.1.1');
select pxp.f_insert_testructura_gui ('RDOC.4.1.1.1.1.1', 'RDOC.4.1.1.1.1');
select pxp.f_insert_testructura_gui ('VBDOC.1', 'VBDOC');
select pxp.f_insert_testructura_gui ('VBDOC.2', 'VBDOC');
select pxp.f_insert_testructura_gui ('VBDOC.3', 'VBDOC');
select pxp.f_insert_testructura_gui ('VBDOC.4', 'VBDOC');
select pxp.f_insert_testructura_gui ('VBDOC.5', 'VBDOC');
select pxp.f_insert_testructura_gui ('VBDOC.1.1', 'VBDOC.1');
select pxp.f_insert_testructura_gui ('VBDOC.1.1.1', 'VBDOC.1.1');
select pxp.f_insert_testructura_gui ('VBDOC.1.1.2', 'VBDOC.1.1');
select pxp.f_insert_testructura_gui ('VBDOC.1.1.3', 'VBDOC.1.1');
select pxp.f_insert_testructura_gui ('VBDOC.1.1.4', 'VBDOC.1.1');
select pxp.f_insert_testructura_gui ('VBDOC.1.1.5', 'VBDOC.1.1');
select pxp.f_insert_testructura_gui ('VBDOC.4.1', 'VBDOC.4');
select pxp.f_insert_testructura_gui ('VBDOC.4.1.1', 'VBDOC.4.1');
select pxp.f_insert_testructura_gui ('VBDOC.4.1.2', 'VBDOC.4.1');
select pxp.f_insert_testructura_gui ('VBDOC.4.1.3', 'VBDOC.4.1');
select pxp.f_insert_testructura_gui ('VBDOC.4.1.1.1', 'VBDOC.4.1.1');
select pxp.f_insert_testructura_gui ('VBDOC.4.1.1.1.1', 'VBDOC.4.1.1.1');
select pxp.f_insert_testructura_gui ('VBDOC.4.1.1.1.1.1', 'VBDOC.4.1.1.1.1');
select pxp.f_insert_tprocedimiento_gui ('seg_TDO_INS', 'TDO', 'no');
select pxp.f_insert_tprocedimiento_gui ('seg_TDO_MOD', 'TDO', 'no');
select pxp.f_insert_tprocedimiento_gui ('seg_TDO_ELI', 'TDO', 'no');
select pxp.f_insert_tprocedimiento_gui ('seg_TDO_SEL', 'TDO', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_INFREG_SEL', 'RDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('seg_TDO_SEL', 'RDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_INF_INS', 'RDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_INF_MOD', 'RDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_INF_ELI', 'RDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_INF_SEL', 'RDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_GATNREP_SEL', 'RDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_SIGEST_IME', 'RDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_ANTEST_IME', 'RDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_SEL', 'RDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'RDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'RDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERSIGPRO_IME', 'RDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CHKSTA_IME', 'RDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'RDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DEPTIPES_SEL', 'RDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_FUNTIPES_SEL', 'RDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'RDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'RDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'RDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'RDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'RDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'RDOC.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'RDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'RDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'RDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'RDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'RDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPPROC_SEL', 'RDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'RDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_INS', 'RDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_MOD', 'RDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_ELI', 'RDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_SEL', 'RDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'RDOC.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'RDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'RDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'RDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'RDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'RDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_SEL', 'RDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'RDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_LUG_SEL', 'RDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_LUG_ARB_SEL', 'RDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_INS', 'RDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_MOD', 'RDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_ELI', 'RDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_SEL', 'RDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'RDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_SEL', 'RDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSONMIN_SEL', 'RDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('OR_FUNCUE_INS', 'RDOC.4.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('OR_FUNCUE_MOD', 'RDOC.4.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('OR_FUNCUE_ELI', 'RDOC.4.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('OR_FUNCUE_SEL', 'RDOC.4.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_INSTIT_SEL', 'RDOC.4.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_INSTIT_INS', 'RDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_INSTIT_MOD', 'RDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_INSTIT_ELI', 'RDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_INSTIT_SEL', 'RDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_SEL', 'RDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSONMIN_SEL', 'RDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_INS', 'RDOC.4.1.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_MOD', 'RDOC.4.1.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_ELI', 'RDOC.4.1.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSONMIN_SEL', 'RDOC.4.1.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_UPFOTOPER_MOD', 'RDOC.4.1.1.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_ESPCIA_SEL', 'RDOC.4.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_RHESFU_INS', 'RDOC.4.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_RHESFU_MOD', 'RDOC.4.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_RHESFU_ELI', 'RDOC.4.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_RHESFU_SEL', 'RDOC.4.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_INS', 'RDOC.4.1.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_MOD', 'RDOC.4.1.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_ELI', 'RDOC.4.1.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSONMIN_SEL', 'RDOC.4.1.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_LUG_SEL', 'RDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_LUG_ARB_SEL', 'RDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_INS', 'RDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_MOD', 'RDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_ELI', 'RDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_SEL', 'RDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'RDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_SEL', 'RDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSONMIN_SEL', 'RDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('seg_TDO_SEL', 'VBDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_INF_INS', 'VBDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_INF_MOD', 'VBDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_INF_ELI', 'VBDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_INF_SEL', 'VBDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_INFREG_SEL', 'VBDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_GATNREP_SEL', 'VBDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_SIGEST_IME', 'VBDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_ANTEST_IME', 'VBDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_SEL', 'VBDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'VBDOC', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'VBDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERSIGPRO_IME', 'VBDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CHKSTA_IME', 'VBDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'VBDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DEPTIPES_SEL', 'VBDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_FUNTIPES_SEL', 'VBDOC.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'VBDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'VBDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'VBDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'VBDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'VBDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'VBDOC.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'VBDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'VBDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'VBDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'VBDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'VBDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPPROC_SEL', 'VBDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'VBDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_INS', 'VBDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_MOD', 'VBDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_ELI', 'VBDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_SEL', 'VBDOC.1.1.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'VBDOC.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'VBDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'VBDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'VBDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'VBDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'VBDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_SEL', 'VBDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'VBDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_LUG_SEL', 'VBDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_LUG_ARB_SEL', 'VBDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_INS', 'VBDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_MOD', 'VBDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_ELI', 'VBDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_SEL', 'VBDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'VBDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_SEL', 'VBDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSONMIN_SEL', 'VBDOC.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('OR_FUNCUE_INS', 'VBDOC.4.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('OR_FUNCUE_MOD', 'VBDOC.4.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('OR_FUNCUE_ELI', 'VBDOC.4.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('OR_FUNCUE_SEL', 'VBDOC.4.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_INSTIT_SEL', 'VBDOC.4.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_INSTIT_INS', 'VBDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_INSTIT_MOD', 'VBDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_INSTIT_ELI', 'VBDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_INSTIT_SEL', 'VBDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_SEL', 'VBDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSONMIN_SEL', 'VBDOC.4.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_INS', 'VBDOC.4.1.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_MOD', 'VBDOC.4.1.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_ELI', 'VBDOC.4.1.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSONMIN_SEL', 'VBDOC.4.1.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_UPFOTOPER_MOD', 'VBDOC.4.1.1.1.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_ESPCIA_SEL', 'VBDOC.4.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_RHESFU_INS', 'VBDOC.4.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_RHESFU_MOD', 'VBDOC.4.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_RHESFU_ELI', 'VBDOC.4.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_RHESFU_SEL', 'VBDOC.4.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_INS', 'VBDOC.4.1.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_MOD', 'VBDOC.4.1.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_ELI', 'VBDOC.4.1.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSONMIN_SEL', 'VBDOC.4.1.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_LUG_SEL', 'VBDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_LUG_ARB_SEL', 'VBDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_INS', 'VBDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_MOD', 'VBDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_ELI', 'VBDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIO_SEL', 'VBDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'VBDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSON_SEL', 'VBDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_PERSONMIN_SEL', 'VBDOC.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'RDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'RDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'RDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'RDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'RDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'RDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'RDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'RDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DHW_SEL', 'RDOC.1.1.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'RDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'RDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'RDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'RDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_OBS_INS', 'RDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_OBS_MOD', 'RDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_OBS_ELI', 'RDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_OBS_SEL', 'RDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_OBSFUN_SEL', 'RDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CERRAROBS_MOD', 'RDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'VBDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'VBDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'VBDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'VBDOC.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'VBDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'VBDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'VBDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'VBDOC.1.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DHW_SEL', 'VBDOC.1.1.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'VBDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'VBDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'VBDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'VBDOC.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_OBS_INS', 'VBDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_OBS_MOD', 'VBDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_OBS_ELI', 'VBDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_OBS_SEL', 'VBDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_OBSFUN_SEL', 'VBDOC.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CERRAROBS_MOD', 'VBDOC.4', 'no');
select pxp.f_insert_tgui_rol ('TDO', 'SDOC');
select pxp.f_insert_tgui_rol ('SEGDOC', 'SDOC');
select pxp.f_insert_tgui_rol ('SISTEMA', 'SDOC');
select pxp.f_delete_tgui_rol ('RDOC', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('SEGDOC', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('SISTEMA', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.3', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.1', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.1.1', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.1.1.3', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.1.1.1', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.1.1.4', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.1.1.2', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.1.1.5', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.4', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.4.1', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.4.1.3', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.4.1.1', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.4.1.1.1', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.4.1.1.1.1', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.4.1.1.1.1.1', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.4.1.2', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.2', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('RDOC.5', 'SEG-Registro');
select pxp.f_delete_tgui_rol ('VBDOC', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('SEGDOC', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('SISTEMA', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.3', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.1', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.1.1', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.1.1.3', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.1.1.1', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.1.1.4', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.1.1.2', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.1.1.5', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.4', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.4.1', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.4.1.3', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.4.1.1', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.4.1.1.1', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.4.1.1.1.1', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.4.1.1.1.1.1', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.4.1.2', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.2', 'SEG - VoBo');
select pxp.f_delete_tgui_rol ('VBDOC.5', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('SEGDOC', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('SISTEMA', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.3', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.1', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.1.1', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.1.1.3', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.1.1.1', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.1.1.4', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.1.1.2', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.1.1.5', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.4', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.4.1', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.4.1.3', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.4.1.2', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.4.1.1', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.4.1.1.1', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.4.1.1.1.1', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.4.1.1.1.1.1', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.2', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('VBDOC.5', 'SEG - VoBo');
select pxp.f_insert_tgui_rol ('RDOC', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('SEGDOC', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('SISTEMA', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.3', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.1', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.1.1', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.1.1.3', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.1.1.1', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.1.1.4', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.1.1.2', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.1.1.5', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.4', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.4.1', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.4.1.3', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.4.1.2', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.4.1.1', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.4.1.1.1', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.4.1.1.1.1', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.4.1.1.1.1.1', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.2', 'SEG-Registro');
select pxp.f_insert_tgui_rol ('RDOC.5', 'SEG-Registro');
select pxp.f_insert_trol_procedimiento_gui ('SDOC', 'seg_TDO_INS', 'TDO');
select pxp.f_insert_trol_procedimiento_gui ('SDOC', 'seg_TDO_MOD', 'TDO');
select pxp.f_delete_trol_procedimiento_gui ('SDOC', 'seg_TDO_ELI', 'TDO');
select pxp.f_insert_trol_procedimiento_gui ('SDOC', 'seg_TDO_SEL', 'TDO');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_INFREG_SEL', 'RDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'seg_TDO_SEL', 'RDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_INF_INS', 'RDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_INF_MOD', 'RDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_INF_ELI', 'RDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_INF_SEL', 'RDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_GATNREP_SEL', 'RDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_SIGEST_IME', 'RDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_ANTEST_IME', 'RDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_SEL', 'RDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIOCAR_SEL', 'RDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPDW_SEL', 'RDOC.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_MOD', 'RDOC.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_ELI', 'RDOC.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_SEL', 'RDOC.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_CABMOM_IME', 'RDOC.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DOCWFAR_MOD', 'RDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_VERSIGPRO_IME', 'RDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_CHKSTA_IME', 'RDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPES_SEL', 'RDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DEPTIPES_SEL', 'RDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_FUNTIPES_SEL', 'RDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPDW_SEL', 'RDOC.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_MOD', 'RDOC.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_ELI', 'RDOC.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_SEL', 'RDOC.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_CABMOM_IME', 'RDOC.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DOCWFAR_MOD', 'RDOC.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPPROC_SEL', 'RDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPES_SEL', 'RDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DES_INS', 'RDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DES_MOD', 'RDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DES_ELI', 'RDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DES_SEL', 'RDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPDW_SEL', 'RDOC.1.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_MOD', 'RDOC.1.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_ELI', 'RDOC.1.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_SEL', 'RDOC.1.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_CABMOM_IME', 'RDOC.1.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_SEL', 'RDOC.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIOCAR_SEL', 'RDOC.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'PM_LUG_SEL', 'RDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'PM_LUG_ARB_SEL', 'RDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_INS', 'RDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_MOD', 'RDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_ELI', 'RDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_SEL', 'RDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIOCAR_SEL', 'RDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_SEL', 'RDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSONMIN_SEL', 'RDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_INS', 'RDOC.4.1.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_MOD', 'RDOC.4.1.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_ELI', 'RDOC.4.1.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSONMIN_SEL', 'RDOC.4.1.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'OR_FUNCUE_INS', 'RDOC.4.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'OR_FUNCUE_MOD', 'RDOC.4.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'OR_FUNCUE_ELI', 'RDOC.4.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'OR_FUNCUE_SEL', 'RDOC.4.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'PM_INSTIT_SEL', 'RDOC.4.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'PM_INSTIT_INS', 'RDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'PM_INSTIT_MOD', 'RDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'PM_INSTIT_ELI', 'RDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'PM_INSTIT_SEL', 'RDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_SEL', 'RDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSONMIN_SEL', 'RDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_INS', 'RDOC.4.1.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_MOD', 'RDOC.4.1.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_ELI', 'RDOC.4.1.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSONMIN_SEL', 'RDOC.4.1.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_UPFOTOPER_MOD', 'RDOC.4.1.1.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_ESPCIA_SEL', 'RDOC.4.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_RHESFU_INS', 'RDOC.4.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_RHESFU_MOD', 'RDOC.4.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_RHESFU_ELI', 'RDOC.4.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_RHESFU_SEL', 'RDOC.4.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'WF_DOCWFAR_MOD', 'RDOC.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'PM_LUG_SEL', 'RDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'PM_LUG_ARB_SEL', 'RDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_INS', 'RDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_MOD', 'RDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_ELI', 'RDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_SEL', 'RDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIOCAR_SEL', 'RDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_SEL', 'RDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSONMIN_SEL', 'RDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'seg_TDO_SEL', 'VBDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_INF_INS', 'VBDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_INF_MOD', 'VBDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_INF_ELI', 'VBDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_INF_SEL', 'VBDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_INFREG_SEL', 'VBDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_GATNREP_SEL', 'VBDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_SIGEST_IME', 'VBDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_ANTEST_IME', 'VBDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_SEL', 'VBDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIOCAR_SEL', 'VBDOC');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPDW_SEL', 'VBDOC.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_MOD', 'VBDOC.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_ELI', 'VBDOC.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_SEL', 'VBDOC.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_CABMOM_IME', 'VBDOC.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DOCWFAR_MOD', 'VBDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_VERSIGPRO_IME', 'VBDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_CHKSTA_IME', 'VBDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPES_SEL', 'VBDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DEPTIPES_SEL', 'VBDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_FUNTIPES_SEL', 'VBDOC.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPDW_SEL', 'VBDOC.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_MOD', 'VBDOC.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_ELI', 'VBDOC.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_SEL', 'VBDOC.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_CABMOM_IME', 'VBDOC.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DOCWFAR_MOD', 'VBDOC.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPPROC_SEL', 'VBDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPES_SEL', 'VBDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DES_INS', 'VBDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DES_MOD', 'VBDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DES_ELI', 'VBDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DES_SEL', 'VBDOC.1.1.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPDW_SEL', 'VBDOC.1.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_MOD', 'VBDOC.1.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_ELI', 'VBDOC.1.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_SEL', 'VBDOC.1.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_CABMOM_IME', 'VBDOC.1.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_SEL', 'VBDOC.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIOCAR_SEL', 'VBDOC.4');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'PM_LUG_SEL', 'VBDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'PM_LUG_ARB_SEL', 'VBDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_INS', 'VBDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_MOD', 'VBDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_ELI', 'VBDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_SEL', 'VBDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIOCAR_SEL', 'VBDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_SEL', 'VBDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSONMIN_SEL', 'VBDOC.4.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_INS', 'VBDOC.4.1.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_MOD', 'VBDOC.4.1.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_ELI', 'VBDOC.4.1.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSONMIN_SEL', 'VBDOC.4.1.3');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'OR_FUNCUE_INS', 'VBDOC.4.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'OR_FUNCUE_MOD', 'VBDOC.4.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'OR_FUNCUE_ELI', 'VBDOC.4.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'OR_FUNCUE_SEL', 'VBDOC.4.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'PM_INSTIT_SEL', 'VBDOC.4.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'PM_INSTIT_INS', 'VBDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'PM_INSTIT_MOD', 'VBDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'PM_INSTIT_ELI', 'VBDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'PM_INSTIT_SEL', 'VBDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_SEL', 'VBDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSONMIN_SEL', 'VBDOC.4.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_INS', 'VBDOC.4.1.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_MOD', 'VBDOC.4.1.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_ELI', 'VBDOC.4.1.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSONMIN_SEL', 'VBDOC.4.1.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_UPFOTOPER_MOD', 'VBDOC.4.1.1.1.1.1');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_ESPCIA_SEL', 'VBDOC.4.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_RHESFU_INS', 'VBDOC.4.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_RHESFU_MOD', 'VBDOC.4.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_RHESFU_ELI', 'VBDOC.4.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_RHESFU_SEL', 'VBDOC.4.1.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'WF_DOCWFAR_MOD', 'VBDOC.2');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'PM_LUG_SEL', 'VBDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'PM_LUG_ARB_SEL', 'VBDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_INS', 'VBDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_MOD', 'VBDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_ELI', 'VBDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_SEL', 'VBDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIOCAR_SEL', 'VBDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_SEL', 'VBDOC.5');
select pxp.f_delete_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSONMIN_SEL', 'VBDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'seg_TDO_SEL', 'VBDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_INF_INS', 'VBDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_INF_MOD', 'VBDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_INF_ELI', 'VBDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_INF_SEL', 'VBDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_INFREG_SEL', 'VBDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_GATNREP_SEL', 'VBDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_SIGEST_IME', 'VBDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_ANTEST_IME', 'VBDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_SEL', 'VBDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIOCAR_SEL', 'VBDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPDW_SEL', 'VBDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_MOD', 'VBDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_ELI', 'VBDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_SEL', 'VBDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_CABMOM_IME', 'VBDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_VERDOC_IME', 'VBDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIDOCPLAN_SEL', 'VBDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_VISTA_SEL', 'VBDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_INS', 'VBDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DOCWFAR_MOD', 'VBDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_VERSIGPRO_IME', 'VBDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_CHKSTA_IME', 'VBDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPES_SEL', 'VBDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DEPTIPES_SEL', 'VBDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_FUNTIPES_SEL', 'VBDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPDW_SEL', 'VBDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_MOD', 'VBDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_ELI', 'VBDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_SEL', 'VBDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_CABMOM_IME', 'VBDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_VERDOC_IME', 'VBDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIDOCPLAN_SEL', 'VBDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_VISTA_SEL', 'VBDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_INS', 'VBDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DHW_SEL', 'VBDOC.1.1.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DOCWFAR_MOD', 'VBDOC.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPPROC_SEL', 'VBDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPES_SEL', 'VBDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DES_INS', 'VBDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DES_MOD', 'VBDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DES_ELI', 'VBDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DES_SEL', 'VBDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIPDW_SEL', 'VBDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_MOD', 'VBDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_ELI', 'VBDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_SEL', 'VBDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_CABMOM_IME', 'VBDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_VERDOC_IME', 'VBDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_TIDOCPLAN_SEL', 'VBDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_VISTA_SEL', 'VBDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DWF_INS', 'VBDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_SEL', 'VBDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIOCAR_SEL', 'VBDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_OBS_INS', 'VBDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_OBS_MOD', 'VBDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_OBS_ELI', 'VBDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_OBS_SEL', 'VBDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_OBSFUN_SEL', 'VBDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_CERRAROBS_MOD', 'VBDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'PM_LUG_SEL', 'VBDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'PM_LUG_ARB_SEL', 'VBDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_INS', 'VBDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_MOD', 'VBDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_ELI', 'VBDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_SEL', 'VBDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIOCAR_SEL', 'VBDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_SEL', 'VBDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSONMIN_SEL', 'VBDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_INS', 'VBDOC.4.1.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_MOD', 'VBDOC.4.1.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_ELI', 'VBDOC.4.1.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSONMIN_SEL', 'VBDOC.4.1.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_ESPCIA_SEL', 'VBDOC.4.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_RHESFU_INS', 'VBDOC.4.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_RHESFU_MOD', 'VBDOC.4.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_RHESFU_ELI', 'VBDOC.4.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_RHESFU_SEL', 'VBDOC.4.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'OR_FUNCUE_INS', 'VBDOC.4.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'OR_FUNCUE_MOD', 'VBDOC.4.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'OR_FUNCUE_ELI', 'VBDOC.4.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'OR_FUNCUE_SEL', 'VBDOC.4.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'PM_INSTIT_SEL', 'VBDOC.4.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'PM_INSTIT_INS', 'VBDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'PM_INSTIT_MOD', 'VBDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'PM_INSTIT_ELI', 'VBDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'PM_INSTIT_SEL', 'VBDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_SEL', 'VBDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSONMIN_SEL', 'VBDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_INS', 'VBDOC.4.1.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_MOD', 'VBDOC.4.1.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_ELI', 'VBDOC.4.1.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSONMIN_SEL', 'VBDOC.4.1.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_UPFOTOPER_MOD', 'VBDOC.4.1.1.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'WF_DOCWFAR_MOD', 'VBDOC.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'PM_LUG_SEL', 'VBDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'PM_LUG_ARB_SEL', 'VBDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_INS', 'VBDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_MOD', 'VBDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_ELI', 'VBDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIO_SEL', 'VBDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'RH_FUNCIOCAR_SEL', 'VBDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSON_SEL', 'VBDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG - VoBo', 'SEG_PERSONMIN_SEL', 'VBDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_INFREG_SEL', 'RDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'seg_TDO_SEL', 'RDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_INF_INS', 'RDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_INF_MOD', 'RDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_INF_ELI', 'RDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_INF_SEL', 'RDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_GATNREP_SEL', 'RDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_SIGEST_IME', 'RDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_ANTEST_IME', 'RDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_SEL', 'RDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIOCAR_SEL', 'RDOC');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPDW_SEL', 'RDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_MOD', 'RDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_ELI', 'RDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_SEL', 'RDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_CABMOM_IME', 'RDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_VERDOC_IME', 'RDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_TIDOCPLAN_SEL', 'RDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_VISTA_SEL', 'RDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_INS', 'RDOC.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DOCWFAR_MOD', 'RDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_VERSIGPRO_IME', 'RDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_CHKSTA_IME', 'RDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPES_SEL', 'RDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DEPTIPES_SEL', 'RDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_FUNTIPES_SEL', 'RDOC.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPDW_SEL', 'RDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_MOD', 'RDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_ELI', 'RDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_SEL', 'RDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_CABMOM_IME', 'RDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_VERDOC_IME', 'RDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_TIDOCPLAN_SEL', 'RDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_VISTA_SEL', 'RDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_INS', 'RDOC.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DHW_SEL', 'RDOC.1.1.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DOCWFAR_MOD', 'RDOC.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPPROC_SEL', 'RDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPES_SEL', 'RDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DES_INS', 'RDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DES_MOD', 'RDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DES_ELI', 'RDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DES_SEL', 'RDOC.1.1.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_TIPDW_SEL', 'RDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_MOD', 'RDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_ELI', 'RDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_SEL', 'RDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_CABMOM_IME', 'RDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_VERDOC_IME', 'RDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_TIDOCPLAN_SEL', 'RDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_VISTA_SEL', 'RDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DWF_INS', 'RDOC.1.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_SEL', 'RDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIOCAR_SEL', 'RDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_OBS_INS', 'RDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_OBS_MOD', 'RDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_OBS_ELI', 'RDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_OBS_SEL', 'RDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_OBSFUN_SEL', 'RDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_CERRAROBS_MOD', 'RDOC.4');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'PM_LUG_SEL', 'RDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'PM_LUG_ARB_SEL', 'RDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_INS', 'RDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_MOD', 'RDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_ELI', 'RDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_SEL', 'RDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIOCAR_SEL', 'RDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_SEL', 'RDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSONMIN_SEL', 'RDOC.4.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_INS', 'RDOC.4.1.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_MOD', 'RDOC.4.1.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_ELI', 'RDOC.4.1.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSONMIN_SEL', 'RDOC.4.1.3');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_ESPCIA_SEL', 'RDOC.4.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_RHESFU_INS', 'RDOC.4.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_RHESFU_MOD', 'RDOC.4.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_RHESFU_ELI', 'RDOC.4.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_RHESFU_SEL', 'RDOC.4.1.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'OR_FUNCUE_INS', 'RDOC.4.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'OR_FUNCUE_MOD', 'RDOC.4.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'OR_FUNCUE_ELI', 'RDOC.4.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'OR_FUNCUE_SEL', 'RDOC.4.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'PM_INSTIT_SEL', 'RDOC.4.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'PM_INSTIT_INS', 'RDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'PM_INSTIT_MOD', 'RDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'PM_INSTIT_ELI', 'RDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'PM_INSTIT_SEL', 'RDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_SEL', 'RDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSONMIN_SEL', 'RDOC.4.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_INS', 'RDOC.4.1.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_MOD', 'RDOC.4.1.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_ELI', 'RDOC.4.1.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSONMIN_SEL', 'RDOC.4.1.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_UPFOTOPER_MOD', 'RDOC.4.1.1.1.1.1');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'WF_DOCWFAR_MOD', 'RDOC.2');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'PM_LUG_SEL', 'RDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'PM_LUG_ARB_SEL', 'RDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_INS', 'RDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_MOD', 'RDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_ELI', 'RDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIO_SEL', 'RDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'RH_FUNCIOCAR_SEL', 'RDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSON_SEL', 'RDOC.5');
select pxp.f_insert_trol_procedimiento_gui ('SEG-Registro', 'SEG_PERSONMIN_SEL', 'RDOC.5');

/***********************************F-DEP-RAC-SEGDOC-0-01/02/2017*****************************************/

